language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - export DJANGO_SETTINGS_MODULE=teracy.html5boilerplate.test_settings
install:
  - pip install -r requirements/dev.txt
script:
  - flake8 --max-complexity 12 .
  - coverage run --branch --source=teracy `which nosetests` -v
  - coverage report --omit=*/__init__.py,teracy/html5boilerplate/test*
  - pylint --rcfile .pylintrc *.py teracy || exit 0
